package com.example.SoapAPI;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 6.0.1.1
//
// Created by Quasar Development 
//
//----------------------------------------------------

/**
 * This interface was generated with EasyWSDL plugin,
 * SOAP was already used in the project for login/logout functionalities
 * (some other functions were written in the SOAP class but not used finally)
 * the other functions can be further used for working with SOAP
 */

import java.util.Date;


public interface EPSDateTimeConverter
{
    java.util.Date convertDateTime(String strDate);
    java.util.Date convertTime(String strDate);
    java.util.Date convertDate(String strDate);
    String convertDuration(String value);
    String getStringFromDateTime(Date value);
    String getStringFromDate(Date value);
    String getStringFromTime(Date value);
    String getStringFromDuration(String value);
}