package com.example.SoapAPI.WSDLclasses;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 6.0.1.1
//
// Created by Quasar Development 
//
//----------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public  class SEDilUserData extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    public Integer usr_id=0;
    
    public String login;
    
    public String passwd;
    
    public String firstname;
    
    public String lastname;
    
    public String title;
    
    public String gender;
    
    public String email;
    
    public String second_email;
    
    public String institution;
    
    public String street;
    
    public String city;
    
    public String zipcode;
    
    public String country;
    
    public String phone_office;
    
    public String last_login;
    
    public String last_update;
    
    public String create_date;
    
    public String hobby;
    
    public String department;
    
    public String phone_home;
    
    public String phone_mobile;
    
    public String fax;
    
    public Integer time_limit_owner=0;
    
    public Integer time_limit_unlimited=0;
    
    public Integer time_limit_from=0;
    
    public Integer time_limit_until=0;
    
    public Integer time_limit_message=0;
    
    public String referral_comment;
    
    public String matriculation;
    
    public Integer active=0;
    
    public Boolean accepted_agreement=false;
    
    public String approve_date;
    
    public String user_skin;
    
    public String user_style;
    
    public String user_language;
    
    public String import_id;

    

    public void loadFromSoap(java.lang.Object paramObj,SEDExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }


    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,SEDExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("usr_id"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.usr_id = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.usr_id = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("login"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.login = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.login = (String)obj;
                }
                else{
                    this.login = "";
                }
            }
            return true;
        }
        if (info.name.equals("passwd"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.passwd = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.passwd = (String)obj;
                }
                else{
                    this.passwd = "";
                }
            }
            return true;
        }
        if (info.name.equals("firstname"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.firstname = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.firstname = (String)obj;
                }
                else{
                    this.firstname = "";
                }
            }
            return true;
        }
        if (info.name.equals("lastname"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.lastname = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.lastname = (String)obj;
                }
                else{
                    this.lastname = "";
                }
            }
            return true;
        }
        if (info.name.equals("title"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.title = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.title = (String)obj;
                }
                else{
                    this.title = "";
                }
            }
            return true;
        }
        if (info.name.equals("gender"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.gender = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.gender = (String)obj;
                }
                else{
                    this.gender = "";
                }
            }
            return true;
        }
        if (info.name.equals("email"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.email = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.email = (String)obj;
                }
                else{
                    this.email = "";
                }
            }
            return true;
        }
        if (info.name.equals("second_email"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.second_email = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.second_email = (String)obj;
                }
                else{
                    this.second_email = "";
                }
            }
            return true;
        }
        if (info.name.equals("institution"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.institution = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.institution = (String)obj;
                }
                else{
                    this.institution = "";
                }
            }
            return true;
        }
        if (info.name.equals("street"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.street = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.street = (String)obj;
                }
                else{
                    this.street = "";
                }
            }
            return true;
        }
        if (info.name.equals("city"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.city = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.city = (String)obj;
                }
                else{
                    this.city = "";
                }
            }
            return true;
        }
        if (info.name.equals("zipcode"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.zipcode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.zipcode = (String)obj;
                }
                else{
                    this.zipcode = "";
                }
            }
            return true;
        }
        if (info.name.equals("country"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.country = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.country = (String)obj;
                }
                else{
                    this.country = "";
                }
            }
            return true;
        }
        if (info.name.equals("phone_office"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.phone_office = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.phone_office = (String)obj;
                }
                else{
                    this.phone_office = "";
                }
            }
            return true;
        }
        if (info.name.equals("last_login"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.last_login = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.last_login = (String)obj;
                }
                else{
                    this.last_login = "";
                }
            }
            return true;
        }
        if (info.name.equals("last_update"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.last_update = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.last_update = (String)obj;
                }
                else{
                    this.last_update = "";
                }
            }
            return true;
        }
        if (info.name.equals("create_date"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.create_date = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.create_date = (String)obj;
                }
                else{
                    this.create_date = "";
                }
            }
            return true;
        }
        if (info.name.equals("hobby"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.hobby = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.hobby = (String)obj;
                }
                else{
                    this.hobby = "";
                }
            }
            return true;
        }
        if (info.name.equals("department"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.department = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.department = (String)obj;
                }
                else{
                    this.department = "";
                }
            }
            return true;
        }
        if (info.name.equals("phone_home"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.phone_home = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.phone_home = (String)obj;
                }
                else{
                    this.phone_home = "";
                }
            }
            return true;
        }
        if (info.name.equals("phone_mobile"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.phone_mobile = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.phone_mobile = (String)obj;
                }
                else{
                    this.phone_mobile = "";
                }
            }
            return true;
        }
        if (info.name.equals("fax"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.fax = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.fax = (String)obj;
                }
                else{
                    this.fax = "";
                }
            }
            return true;
        }
        if (info.name.equals("time_limit_owner"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.time_limit_owner = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.time_limit_owner = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("time_limit_unlimited"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.time_limit_unlimited = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.time_limit_unlimited = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("time_limit_from"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.time_limit_from = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.time_limit_from = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("time_limit_until"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.time_limit_until = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.time_limit_until = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("time_limit_message"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.time_limit_message = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.time_limit_message = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("referral_comment"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.referral_comment = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.referral_comment = (String)obj;
                }
                else{
                    this.referral_comment = "";
                }
            }
            return true;
        }
        if (info.name.equals("matriculation"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.matriculation = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.matriculation = (String)obj;
                }
                else{
                    this.matriculation = "";
                }
            }
            return true;
        }
        if (info.name.equals("active"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.active = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.active = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("accepted_agreement"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.accepted_agreement = Boolean.valueOf(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.accepted_agreement = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("approve_date"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.approve_date = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.approve_date = (String)obj;
                }
                else{
                    this.approve_date = "";
                }
            }
            return true;
        }
        if (info.name.equals("user_skin"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.user_skin = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.user_skin = (String)obj;
                }
                else{
                    this.user_skin = "";
                }
            }
            return true;
        }
        if (info.name.equals("user_style"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.user_style = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.user_style = (String)obj;
                }
                else{
                    this.user_style = "";
                }
            }
            return true;
        }
        if (info.name.equals("user_language"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.user_language = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.user_language = (String)obj;
                }
                else{
                    this.user_language = "";
                }
            }
            return true;
        }
        if (info.name.equals("import_id"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.import_id = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.import_id = (String)obj;
                }
                else{
                    this.import_id = "";
                }
            }
            return true;
        }
        return false;
    }    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    
    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.usr_id;
        }
        else if(propertyIndex==1)
        {
            return this.login;
        }
        else if(propertyIndex==2)
        {
            return this.passwd;
        }
        else if(propertyIndex==3)
        {
            return this.firstname;
        }
        else if(propertyIndex==4)
        {
            return this.lastname;
        }
        else if(propertyIndex==5)
        {
            return this.title;
        }
        else if(propertyIndex==6)
        {
            return this.gender;
        }
        else if(propertyIndex==7)
        {
            return this.email;
        }
        else if(propertyIndex==8)
        {
            return this.second_email;
        }
        else if(propertyIndex==9)
        {
            return this.institution;
        }
        else if(propertyIndex==10)
        {
            return this.street;
        }
        else if(propertyIndex==11)
        {
            return this.city;
        }
        else if(propertyIndex==12)
        {
            return this.zipcode;
        }
        else if(propertyIndex==13)
        {
            return this.country;
        }
        else if(propertyIndex==14)
        {
            return this.phone_office;
        }
        else if(propertyIndex==15)
        {
            return this.last_login;
        }
        else if(propertyIndex==16)
        {
            return this.last_update;
        }
        else if(propertyIndex==17)
        {
            return this.create_date;
        }
        else if(propertyIndex==18)
        {
            return this.hobby;
        }
        else if(propertyIndex==19)
        {
            return this.department;
        }
        else if(propertyIndex==20)
        {
            return this.phone_home;
        }
        else if(propertyIndex==21)
        {
            return this.phone_mobile;
        }
        else if(propertyIndex==22)
        {
            return this.fax;
        }
        else if(propertyIndex==23)
        {
            return this.time_limit_owner;
        }
        else if(propertyIndex==24)
        {
            return this.time_limit_unlimited;
        }
        else if(propertyIndex==25)
        {
            return this.time_limit_from;
        }
        else if(propertyIndex==26)
        {
            return this.time_limit_until;
        }
        else if(propertyIndex==27)
        {
            return this.time_limit_message;
        }
        else if(propertyIndex==28)
        {
            return this.referral_comment;
        }
        else if(propertyIndex==29)
        {
            return this.matriculation;
        }
        else if(propertyIndex==30)
        {
            return this.active;
        }
        else if(propertyIndex==31)
        {
            return this.accepted_agreement;
        }
        else if(propertyIndex==32)
        {
            return this.approve_date;
        }
        else if(propertyIndex==33)
        {
            return this.user_skin;
        }
        else if(propertyIndex==34)
        {
            return this.user_style;
        }
        else if(propertyIndex==35)
        {
            return this.user_language;
        }
        else if(propertyIndex==36)
        {
            return this.import_id;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 37;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
            if(propertyIndex==0)
            {
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "usr_id";
                info.namespace= "";
            }
            else if(propertyIndex==1)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "login";
                info.namespace= "";
            }
            else if(propertyIndex==2)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "passwd";
                info.namespace= "";
            }
            else if(propertyIndex==3)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "firstname";
                info.namespace= "";
            }
            else if(propertyIndex==4)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "lastname";
                info.namespace= "";
            }
            else if(propertyIndex==5)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "title";
                info.namespace= "";
            }
            else if(propertyIndex==6)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "gender";
                info.namespace= "";
            }
            else if(propertyIndex==7)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "email";
                info.namespace= "";
            }
            else if(propertyIndex==8)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "second_email";
                info.namespace= "";
            }
            else if(propertyIndex==9)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "institution";
                info.namespace= "";
            }
            else if(propertyIndex==10)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "street";
                info.namespace= "";
            }
            else if(propertyIndex==11)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "city";
                info.namespace= "";
            }
            else if(propertyIndex==12)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "zipcode";
                info.namespace= "";
            }
            else if(propertyIndex==13)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "country";
                info.namespace= "";
            }
            else if(propertyIndex==14)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "phone_office";
                info.namespace= "";
            }
            else if(propertyIndex==15)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "last_login";
                info.namespace= "";
            }
            else if(propertyIndex==16)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "last_update";
                info.namespace= "";
            }
            else if(propertyIndex==17)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "create_date";
                info.namespace= "";
            }
            else if(propertyIndex==18)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "hobby";
                info.namespace= "";
            }
            else if(propertyIndex==19)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "department";
                info.namespace= "";
            }
            else if(propertyIndex==20)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "phone_home";
                info.namespace= "";
            }
            else if(propertyIndex==21)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "phone_mobile";
                info.namespace= "";
            }
            else if(propertyIndex==22)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "fax";
                info.namespace= "";
            }
            else if(propertyIndex==23)
            {
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "time_limit_owner";
                info.namespace= "";
            }
            else if(propertyIndex==24)
            {
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "time_limit_unlimited";
                info.namespace= "";
            }
            else if(propertyIndex==25)
            {
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "time_limit_from";
                info.namespace= "";
            }
            else if(propertyIndex==26)
            {
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "time_limit_until";
                info.namespace= "";
            }
            else if(propertyIndex==27)
            {
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "time_limit_message";
                info.namespace= "";
            }
            else if(propertyIndex==28)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "referral_comment";
                info.namespace= "";
            }
            else if(propertyIndex==29)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "matriculation";
                info.namespace= "";
            }
            else if(propertyIndex==30)
            {
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "active";
                info.namespace= "";
            }
            else if(propertyIndex==31)
            {
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "accepted_agreement";
                info.namespace= "";
            }
            else if(propertyIndex==32)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "approve_date";
                info.namespace= "";
            }
            else if(propertyIndex==33)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "user_skin";
                info.namespace= "";
            }
            else if(propertyIndex==34)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "user_style";
                info.namespace= "";
            }
            else if(propertyIndex==35)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "user_language";
                info.namespace= "";
            }
            else if(propertyIndex==36)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "import_id";
                info.namespace= "";
            }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
